build site:
  image: node:latest
  stage: build
  script:
    - npm cache clean -f
    - npm install -g n
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist