<template>
  <transition name="fade">
    <div v-if="imagesBoxDisplayed" class="box">
      <!-- Modal content -->
      <div class="content">
        <span class="close" @click="closeBox()">&times;</span>

        <transition name="fade">
          <div v-if="!imagesBoxSubmitting && Object.keys(imagesBoxErrors).length !== 0" class="alert"
               v-bind:class="{ 'danger' : !imagesBoxSuccess}">
            <div v-for="(v, k) in imagesBoxErrors.errors"
                 v-bind:key="k">
              <p v-for="error in v" v-bind:key="error">
                {{ error }}
              </p>
            </div>
          </div>
        </transition>

        <h3>{{ getTranslation(titleName()) }}</h3>

        <form @submit.prevent="sendForm">

          <div class="input-group">
            <label for="title">{{ getTranslation('views.images.form.title') }}</label>
            <input id="title"
                   v-model="imagesBoxItem.title"
                   :disabled="imagesBoxSubmitting"
                   required
                   type="text"
                   v-bind:class="{'error' : imagesBoxErrors && imagesBoxErrors.errors && imagesBoxErrors.errors.title}">
          </div>

          <div class="input-group">
            <label for="description">{{ getTranslation('views.images.form.description') }}</label>
            <textarea id="description"
                      v-model="imagesBoxItem.description"
                      :disabled="imagesBoxSubmitting"
                      cols="30"
                      required
                      rows="5"
                      v-bind:class="{'error' : imagesBoxErrors && imagesBoxErrors.errors && imagesBoxErrors.errors.description}"/>
          </div>

          <div class="input-group">
            <label for="file">{{ getTranslation('views.images.form.image') }}</label>
            <input id="file"
                   :disabled="imagesBoxSubmitting"
                   type="file"
                   v-bind:class="{'error' : imagesBoxErrors && imagesBoxErrors.errors && imagesBoxErrors.errors.image}"
                   @change="onFileChange"/>
          </div>

          <div class="footer">
            <button :disabled="imagesBoxSubmitting" class="submit-button button-sm">
              {{ getTranslation(buttonName()) }}
            </button>

            <transition name="fade">
              <beat-loader :color="'orange'" :loading="imagesBoxSubmitting" style="margin-left: 10px"/>
            </transition>
          </div>

        </form>

      </div>

    </div>
  </transition>
</template>

<script>
import {mapGetters} from "vuex";
import {IMAGES_CLOSE_EDIT_BOX} from "@/store/mutations.type";
import {IMAGES_SEND} from "@/store/actions.type";
import BeatLoader from "vue-spinner/src/BeatLoader"

export default {
  name: "ImageEdit",
  components: {
    BeatLoader
  },
  computed: {
    ...mapGetters(["getTranslation", "imagesBoxItem", "imagesBoxDisplayed", "imagesBoxSubmitting", "imagesBoxSuccess", "imagesBoxErrors"])
  },
  methods: {
    closeBox() {
      this.$store.commit(IMAGES_CLOSE_EDIT_BOX);
    },

    isCreated() {
      return this.imagesBoxItem.id !== "";
    },

    sendForm() {
      this.$store.dispatch(IMAGES_SEND, this.isCreated());
    },

    buttonName() {
      let name = "views.images.buttons.";
      return !this.isCreated() ? name + "create" : name + "edit";
    },

    titleName() {
      let name = "views.admin.manage.box-title.";
      return !this.isCreated() ? name + "create" : name + "update";
    },

    onFileChange(e) {
      let files = e.target.files || e.dataTransfer.files;
      if (!files.length)
        return;
      this.imagesBoxItem.file = files[0];
    }

  },
}
</script>

<style scoped>

/* ----------------------------------------------
 * Generated by Animista on 2020-11-15 3:48:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-elliptic-top-fwd
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-elliptic-top-fwd {
  0% {
    -webkit-transform: translateY(-600px) rotateX(-30deg) scale(0);
    transform: translateY(-600px) rotateX(-30deg) scale(0);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
    opacity: 0;
    overflow: hidden;
  }
  100% {
    -webkit-transform: translateY(0) rotateX(0) scale(1);
    transform: translateY(0) rotateX(0) scale(1);
    -webkit-transform-origin: 50% 1400px;
    transform-origin: 50% 1400px;
    opacity: 1;
  }
}

@keyframes slide-in-elliptic-top-fwd {
  0% {
    -webkit-transform: translateY(-600px) rotateX(-30deg) scale(0);
    transform: translateY(-600px) rotateX(-30deg) scale(0);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
    opacity: 0;
    overflow: hidden;
  }
  100% {
    -webkit-transform: translateY(0) rotateX(0) scale(1);
    transform: translateY(0) rotateX(0) scale(1);
    -webkit-transform-origin: 50% 1400px;
    transform-origin: 50% 1400px;
    opacity: 1;
  }
}


.box {
  display: flex;
  position: fixed;
  z-index: 1;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  overflow: auto;
  background-color: rgb(0, 0, 0);
  background-color: rgba(0, 0, 0, 0.4);
}

.box .content {
  background-color: #fefefe;
  margin: auto;
  padding: 20px;
  border: 1px solid #888;
  width: 60%;
  border-radius: 10px;
  -webkit-animation: slide-in-elliptic-top-fwd 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: slide-in-elliptic-top-fwd 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

.box .content h3 {
  margin: 5px 5px 20px;
  text-align: center;
  text-decoration: underline;
}

.box .footer {
  display: flex;
  align-items: center;
}

.close {
  color: #aaaaaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}

@media only screen and (max-width: 790px) {

  .box .content {
    width: 80%;
  }

}

</style>